# Generated by Django 2.2.1 on 2019-08-22 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DEAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEusername', models.TextField(max_length=100)),
                ('DEpassword', models.TextField(max_length=100)),
                ('DEToken', models.TextField(blank=True, max_length=100)),
                ('DETokenDate', models.DateTimeField(blank=True, null=True)),
                ('djangouser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deaccounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
